class CountryInfo {
  final String name;
  final String code;
  final String flagEmoji;

  const CountryInfo({
    required this.name,
    required this.code,
    required this.flagEmoji,
  });
}

/// Complete list of 195 UN-recognized countries with emoji flags.
const List<CountryInfo> allCountries = [
  CountryInfo(name: 'Afghanistan', code: 'AF', flagEmoji: '🇦🇫'),
  CountryInfo(name: 'Albania', code: 'AL', flagEmoji: '🇦🇱'),
  CountryInfo(name: 'Algeria', code: 'DZ', flagEmoji: '🇩🇿'),
  CountryInfo(name: 'Andorra', code: 'AD', flagEmoji: '🇦🇩'),
  CountryInfo(name: 'Angola', code: 'AO', flagEmoji: '🇦🇴'),
  CountryInfo(name: 'Antigua and Barbuda', code: 'AG', flagEmoji: '🇦🇬'),
  CountryInfo(name: 'Argentina', code: 'AR', flagEmoji: '🇦🇷'),
  CountryInfo(name: 'Armenia', code: 'AM', flagEmoji: '🇦🇲'),
  CountryInfo(name: 'Australia', code: 'AU', flagEmoji: '🇦🇺'),
  CountryInfo(name: 'Austria', code: 'AT', flagEmoji: '🇦🇹'),
  CountryInfo(name: 'Azerbaijan', code: 'AZ', flagEmoji: '🇦🇿'),
  CountryInfo(name: 'Bahamas', code: 'BS', flagEmoji: '🇧🇸'),
  CountryInfo(name: 'Bahrain', code: 'BH', flagEmoji: '🇧🇭'),
  CountryInfo(name: 'Bangladesh', code: 'BD', flagEmoji: '🇧🇩'),
  CountryInfo(name: 'Barbados', code: 'BB', flagEmoji: '🇧🇧'),
  CountryInfo(name: 'Belarus', code: 'BY', flagEmoji: '🇧🇾'),
  CountryInfo(name: 'Belgium', code: 'BE', flagEmoji: '🇧🇪'),
  CountryInfo(name: 'Belize', code: 'BZ', flagEmoji: '🇧🇿'),
  CountryInfo(name: 'Benin', code: 'BJ', flagEmoji: '🇧🇯'),
  CountryInfo(name: 'Bhutan', code: 'BT', flagEmoji: '🇧🇹'),
  CountryInfo(name: 'Bolivia', code: 'BO', flagEmoji: '🇧🇴'),
  CountryInfo(name: 'Bosnia and Herzegovina', code: 'BA', flagEmoji: '🇧🇦'),
  CountryInfo(name: 'Botswana', code: 'BW', flagEmoji: '🇧🇼'),
  CountryInfo(name: 'Brazil', code: 'BR', flagEmoji: '🇧🇷'),
  CountryInfo(name: 'Brunei', code: 'BN', flagEmoji: '🇧🇳'),
  CountryInfo(name: 'Bulgaria', code: 'BG', flagEmoji: '🇧🇬'),
  CountryInfo(name: 'Burkina Faso', code: 'BF', flagEmoji: '🇧🇫'),
  CountryInfo(name: 'Burundi', code: 'BI', flagEmoji: '🇧🇮'),
  CountryInfo(name: 'Cabo Verde', code: 'CV', flagEmoji: '🇨🇻'),
  CountryInfo(name: 'Cambodia', code: 'KH', flagEmoji: '🇰🇭'),
  CountryInfo(name: 'Cameroon', code: 'CM', flagEmoji: '🇨🇲'),
  CountryInfo(name: 'Canada', code: 'CA', flagEmoji: '🇨🇦'),
  CountryInfo(name: 'Central African Republic', code: 'CF', flagEmoji: '🇨🇫'),
  CountryInfo(name: 'Chad', code: 'TD', flagEmoji: '🇹🇩'),
  CountryInfo(name: 'Chile', code: 'CL', flagEmoji: '🇨🇱'),
  CountryInfo(name: 'China', code: 'CN', flagEmoji: '🇨🇳'),
  CountryInfo(name: 'Colombia', code: 'CO', flagEmoji: '🇨🇴'),
  CountryInfo(name: 'Comoros', code: 'KM', flagEmoji: '🇰🇲'),
  CountryInfo(name: 'Congo (DRC)', code: 'CD', flagEmoji: '🇨🇩'),
  CountryInfo(name: 'Congo (Republic)', code: 'CG', flagEmoji: '🇨🇬'),
  CountryInfo(name: 'Costa Rica', code: 'CR', flagEmoji: '🇨🇷'),
  CountryInfo(name: "Côte d'Ivoire", code: 'CI', flagEmoji: '🇨🇮'),
  CountryInfo(name: 'Croatia', code: 'HR', flagEmoji: '🇭🇷'),
  CountryInfo(name: 'Cuba', code: 'CU', flagEmoji: '🇨🇺'),
  CountryInfo(name: 'Cyprus', code: 'CY', flagEmoji: '🇨🇾'),
  CountryInfo(name: 'Czech Republic', code: 'CZ', flagEmoji: '🇨🇿'),
  CountryInfo(name: 'Denmark', code: 'DK', flagEmoji: '🇩🇰'),
  CountryInfo(name: 'Djibouti', code: 'DJ', flagEmoji: '🇩🇯'),
  CountryInfo(name: 'Dominica', code: 'DM', flagEmoji: '🇩🇲'),
  CountryInfo(name: 'Dominican Republic', code: 'DO', flagEmoji: '🇩🇴'),
  CountryInfo(name: 'Ecuador', code: 'EC', flagEmoji: '🇪🇨'),
  CountryInfo(name: 'Egypt', code: 'EG', flagEmoji: '🇪🇬'),
  CountryInfo(name: 'El Salvador', code: 'SV', flagEmoji: '🇸🇻'),
  CountryInfo(name: 'Equatorial Guinea', code: 'GQ', flagEmoji: '🇬🇶'),
  CountryInfo(name: 'Eritrea', code: 'ER', flagEmoji: '🇪🇷'),
  CountryInfo(name: 'Estonia', code: 'EE', flagEmoji: '🇪🇪'),
  CountryInfo(name: 'Eswatini', code: 'SZ', flagEmoji: '🇸🇿'),
  CountryInfo(name: 'Ethiopia', code: 'ET', flagEmoji: '🇪🇹'),
  CountryInfo(name: 'Fiji', code: 'FJ', flagEmoji: '🇫🇯'),
  CountryInfo(name: 'Finland', code: 'FI', flagEmoji: '🇫🇮'),
  CountryInfo(name: 'France', code: 'FR', flagEmoji: '🇫🇷'),
  CountryInfo(name: 'Gabon', code: 'GA', flagEmoji: '🇬🇦'),
  CountryInfo(name: 'Gambia', code: 'GM', flagEmoji: '🇬🇲'),
  CountryInfo(name: 'Georgia', code: 'GE', flagEmoji: '🇬🇪'),
  CountryInfo(name: 'Germany', code: 'DE', flagEmoji: '🇩🇪'),
  CountryInfo(name: 'Ghana', code: 'GH', flagEmoji: '🇬🇭'),
  CountryInfo(name: 'Greece', code: 'GR', flagEmoji: '🇬🇷'),
  CountryInfo(name: 'Grenada', code: 'GD', flagEmoji: '🇬🇩'),
  CountryInfo(name: 'Guatemala', code: 'GT', flagEmoji: '🇬🇹'),
  CountryInfo(name: 'Guinea', code: 'GN', flagEmoji: '🇬🇳'),
  CountryInfo(name: 'Guinea-Bissau', code: 'GW', flagEmoji: '🇬🇼'),
  CountryInfo(name: 'Guyana', code: 'GY', flagEmoji: '🇬🇾'),
  CountryInfo(name: 'Haiti', code: 'HT', flagEmoji: '🇭🇹'),
  CountryInfo(name: 'Honduras', code: 'HN', flagEmoji: '🇭🇳'),
  CountryInfo(name: 'Hungary', code: 'HU', flagEmoji: '🇭🇺'),
  CountryInfo(name: 'Iceland', code: 'IS', flagEmoji: '🇮🇸'),
  CountryInfo(name: 'India', code: 'IN', flagEmoji: '🇮🇳'),
  CountryInfo(name: 'Indonesia', code: 'ID', flagEmoji: '🇮🇩'),
  CountryInfo(name: 'Iran', code: 'IR', flagEmoji: '🇮🇷'),
  CountryInfo(name: 'Iraq', code: 'IQ', flagEmoji: '🇮🇶'),
  CountryInfo(name: 'Ireland', code: 'IE', flagEmoji: '🇮🇪'),
  CountryInfo(name: 'Israel', code: 'IL', flagEmoji: '🇮🇱'),
  CountryInfo(name: 'Italy', code: 'IT', flagEmoji: '🇮🇹'),
  CountryInfo(name: 'Jamaica', code: 'JM', flagEmoji: '🇯🇲'),
  CountryInfo(name: 'Japan', code: 'JP', flagEmoji: '🇯🇵'),
  CountryInfo(name: 'Jordan', code: 'JO', flagEmoji: '🇯🇴'),
  CountryInfo(name: 'Kazakhstan', code: 'KZ', flagEmoji: '🇰🇿'),
  CountryInfo(name: 'Kenya', code: 'KE', flagEmoji: '🇰🇪'),
  CountryInfo(name: 'Kiribati', code: 'KI', flagEmoji: '🇰🇮'),
  CountryInfo(name: 'Kuwait', code: 'KW', flagEmoji: '🇰🇼'),
  CountryInfo(name: 'Kyrgyzstan', code: 'KG', flagEmoji: '🇰🇬'),
  CountryInfo(name: 'Laos', code: 'LA', flagEmoji: '🇱🇦'),
  CountryInfo(name: 'Latvia', code: 'LV', flagEmoji: '🇱🇻'),
  CountryInfo(name: 'Lebanon', code: 'LB', flagEmoji: '🇱🇧'),
  CountryInfo(name: 'Lesotho', code: 'LS', flagEmoji: '🇱🇸'),
  CountryInfo(name: 'Liberia', code: 'LR', flagEmoji: '🇱🇷'),
  CountryInfo(name: 'Libya', code: 'LY', flagEmoji: '🇱🇾'),
  CountryInfo(name: 'Liechtenstein', code: 'LI', flagEmoji: '🇱🇮'),
  CountryInfo(name: 'Lithuania', code: 'LT', flagEmoji: '🇱🇹'),
  CountryInfo(name: 'Luxembourg', code: 'LU', flagEmoji: '🇱🇺'),
  CountryInfo(name: 'Madagascar', code: 'MG', flagEmoji: '🇲🇬'),
  CountryInfo(name: 'Malawi', code: 'MW', flagEmoji: '🇲🇼'),
  CountryInfo(name: 'Malaysia', code: 'MY', flagEmoji: '🇲🇾'),
  CountryInfo(name: 'Maldives', code: 'MV', flagEmoji: '🇲🇻'),
  CountryInfo(name: 'Mali', code: 'ML', flagEmoji: '🇲🇱'),
  CountryInfo(name: 'Malta', code: 'MT', flagEmoji: '🇲🇹'),
  CountryInfo(name: 'Marshall Islands', code: 'MH', flagEmoji: '🇲🇭'),
  CountryInfo(name: 'Mauritania', code: 'MR', flagEmoji: '🇲🇷'),
  CountryInfo(name: 'Mauritius', code: 'MU', flagEmoji: '🇲🇺'),
  CountryInfo(name: 'Mexico', code: 'MX', flagEmoji: '🇲🇽'),
  CountryInfo(name: 'Micronesia', code: 'FM', flagEmoji: '🇫🇲'),
  CountryInfo(name: 'Moldova', code: 'MD', flagEmoji: '🇲🇩'),
  CountryInfo(name: 'Monaco', code: 'MC', flagEmoji: '🇲🇨'),
  CountryInfo(name: 'Mongolia', code: 'MN', flagEmoji: '🇲🇳'),
  CountryInfo(name: 'Montenegro', code: 'ME', flagEmoji: '🇲🇪'),
  CountryInfo(name: 'Morocco', code: 'MA', flagEmoji: '🇲🇦'),
  CountryInfo(name: 'Mozambique', code: 'MZ', flagEmoji: '🇲🇿'),
  CountryInfo(name: 'Myanmar', code: 'MM', flagEmoji: '🇲🇲'),
  CountryInfo(name: 'Namibia', code: 'NA', flagEmoji: '🇳🇦'),
  CountryInfo(name: 'Nauru', code: 'NR', flagEmoji: '🇳🇷'),
  CountryInfo(name: 'Nepal', code: 'NP', flagEmoji: '🇳🇵'),
  CountryInfo(name: 'Netherlands', code: 'NL', flagEmoji: '🇳🇱'),
  CountryInfo(name: 'New Zealand', code: 'NZ', flagEmoji: '🇳🇿'),
  CountryInfo(name: 'Nicaragua', code: 'NI', flagEmoji: '🇳🇮'),
  CountryInfo(name: 'Niger', code: 'NE', flagEmoji: '🇳🇪'),
  CountryInfo(name: 'Nigeria', code: 'NG', flagEmoji: '🇳🇬'),
  CountryInfo(name: 'North Korea', code: 'KP', flagEmoji: '🇰🇵'),
  CountryInfo(name: 'North Macedonia', code: 'MK', flagEmoji: '🇲🇰'),
  CountryInfo(name: 'Norway', code: 'NO', flagEmoji: '🇳🇴'),
  CountryInfo(name: 'Oman', code: 'OM', flagEmoji: '🇴🇲'),
  CountryInfo(name: 'Pakistan', code: 'PK', flagEmoji: '🇵🇰'),
  CountryInfo(name: 'Palau', code: 'PW', flagEmoji: '🇵🇼'),
  CountryInfo(name: 'Palestine', code: 'PS', flagEmoji: '🇵🇸'),
  CountryInfo(name: 'Panama', code: 'PA', flagEmoji: '🇵🇦'),
  CountryInfo(name: 'Papua New Guinea', code: 'PG', flagEmoji: '🇵🇬'),
  CountryInfo(name: 'Paraguay', code: 'PY', flagEmoji: '🇵🇾'),
  CountryInfo(name: 'Peru', code: 'PE', flagEmoji: '🇵🇪'),
  CountryInfo(name: 'Philippines', code: 'PH', flagEmoji: '🇵🇭'),
  CountryInfo(name: 'Poland', code: 'PL', flagEmoji: '🇵🇱'),
  CountryInfo(name: 'Portugal', code: 'PT', flagEmoji: '🇵🇹'),
  CountryInfo(name: 'Qatar', code: 'QA', flagEmoji: '🇶🇦'),
  CountryInfo(name: 'Romania', code: 'RO', flagEmoji: '🇷🇴'),
  CountryInfo(name: 'Russia', code: 'RU', flagEmoji: '🇷🇺'),
  CountryInfo(name: 'Rwanda', code: 'RW', flagEmoji: '🇷🇼'),
  CountryInfo(name: 'Saint Kitts and Nevis', code: 'KN', flagEmoji: '🇰🇳'),
  CountryInfo(name: 'Saint Lucia', code: 'LC', flagEmoji: '🇱🇨'),
  CountryInfo(name: 'Saint Vincent and the Grenadines', code: 'VC', flagEmoji: '🇻🇨'),
  CountryInfo(name: 'Samoa', code: 'WS', flagEmoji: '🇼🇸'),
  CountryInfo(name: 'San Marino', code: 'SM', flagEmoji: '🇸🇲'),
  CountryInfo(name: 'São Tomé and Príncipe', code: 'ST', flagEmoji: '🇸🇹'),
  CountryInfo(name: 'Saudi Arabia', code: 'SA', flagEmoji: '🇸🇦'),
  CountryInfo(name: 'Senegal', code: 'SN', flagEmoji: '🇸🇳'),
  CountryInfo(name: 'Serbia', code: 'RS', flagEmoji: '🇷🇸'),
  CountryInfo(name: 'Seychelles', code: 'SC', flagEmoji: '🇸🇨'),
  CountryInfo(name: 'Sierra Leone', code: 'SL', flagEmoji: '🇸🇱'),
  CountryInfo(name: 'Singapore', code: 'SG', flagEmoji: '🇸🇬'),
  CountryInfo(name: 'Slovakia', code: 'SK', flagEmoji: '🇸🇰'),
  CountryInfo(name: 'Slovenia', code: 'SI', flagEmoji: '🇸🇮'),
  CountryInfo(name: 'Solomon Islands', code: 'SB', flagEmoji: '🇸🇧'),
  CountryInfo(name: 'Somalia', code: 'SO', flagEmoji: '🇸🇴'),
  CountryInfo(name: 'South Africa', code: 'ZA', flagEmoji: '🇿🇦'),
  CountryInfo(name: 'South Korea', code: 'KR', flagEmoji: '🇰🇷'),
  CountryInfo(name: 'South Sudan', code: 'SS', flagEmoji: '🇸🇸'),
  CountryInfo(name: 'Spain', code: 'ES', flagEmoji: '🇪🇸'),
  CountryInfo(name: 'Sri Lanka', code: 'LK', flagEmoji: '🇱🇰'),
  CountryInfo(name: 'Sudan', code: 'SD', flagEmoji: '🇸🇩'),
  CountryInfo(name: 'Suriname', code: 'SR', flagEmoji: '🇸🇷'),
  CountryInfo(name: 'Sweden', code: 'SE', flagEmoji: '🇸🇪'),
  CountryInfo(name: 'Switzerland', code: 'CH', flagEmoji: '🇨🇭'),
  CountryInfo(name: 'Syria', code: 'SY', flagEmoji: '🇸🇾'),
  CountryInfo(name: 'Taiwan', code: 'TW', flagEmoji: '🇹🇼'),
  CountryInfo(name: 'Tajikistan', code: 'TJ', flagEmoji: '🇹🇯'),
  CountryInfo(name: 'Tanzania', code: 'TZ', flagEmoji: '🇹🇿'),
  CountryInfo(name: 'Thailand', code: 'TH', flagEmoji: '🇹🇭'),
  CountryInfo(name: 'Timor-Leste', code: 'TL', flagEmoji: '🇹🇱'),
  CountryInfo(name: 'Togo', code: 'TG', flagEmoji: '🇹🇬'),
  CountryInfo(name: 'Tonga', code: 'TO', flagEmoji: '🇹🇴'),
  CountryInfo(name: 'Trinidad and Tobago', code: 'TT', flagEmoji: '🇹🇹'),
  CountryInfo(name: 'Tunisia', code: 'TN', flagEmoji: '🇹🇳'),
  CountryInfo(name: 'Turkey', code: 'TR', flagEmoji: '🇹🇷'),
  CountryInfo(name: 'Turkmenistan', code: 'TM', flagEmoji: '🇹🇲'),
  CountryInfo(name: 'Tuvalu', code: 'TV', flagEmoji: '🇹🇻'),
  CountryInfo(name: 'Uganda', code: 'UG', flagEmoji: '🇺🇬'),
  CountryInfo(name: 'Ukraine', code: 'UA', flagEmoji: '🇺🇦'),
  CountryInfo(name: 'United Arab Emirates', code: 'AE', flagEmoji: '🇦🇪'),
  CountryInfo(name: 'United Kingdom', code: 'GB', flagEmoji: '🇬🇧'),
  CountryInfo(name: 'United States', code: 'US', flagEmoji: '🇺🇸'),
  CountryInfo(name: 'Uruguay', code: 'UY', flagEmoji: '🇺🇾'),
  CountryInfo(name: 'Uzbekistan', code: 'UZ', flagEmoji: '🇺🇿'),
  CountryInfo(name: 'Vanuatu', code: 'VU', flagEmoji: '🇻🇺'),
  CountryInfo(name: 'Vatican City', code: 'VA', flagEmoji: '🇻🇦'),
  CountryInfo(name: 'Venezuela', code: 'VE', flagEmoji: '🇻🇪'),
  CountryInfo(name: 'Vietnam', code: 'VN', flagEmoji: '🇻🇳'),
  CountryInfo(name: 'Yemen', code: 'YE', flagEmoji: '🇾🇪'),
  CountryInfo(name: 'Zambia', code: 'ZM', flagEmoji: '🇿🇲'),
  CountryInfo(name: 'Zimbabwe', code: 'ZW', flagEmoji: '🇿🇼'),
];
